/**
 * Choices on the trial sign-up form. Plain data, shared by the page, the
 * server action and tests.
 */

/** Indian industries and trades, grouped the way owners describe themselves. */
export const INDUSTRIES = [
  "Retail — kirana / general store",
  "Retail — supermarket / departmental store",
  "Retail — mobile & electronics",
  "Retail — pharmacy / chemist",
  "Retail — footwear & fashion",
  "Showroom / outlet",
  "Wholesale / distribution",
  "Stockist / C&F agent",
  "Import / export",
  "E-commerce seller",
  "Manufacturing — engineering / fabrication",
  "Manufacturing — food processing",
  "Manufacturing — plastics / packaging",
  "Manufacturing — chemicals / pharma",
  "Manufacturing — furniture / wood",
  "Textiles / garments",
  "Handloom / handicrafts",
  "Jewellery / gold & silver",
  "Printing / publishing",
  "Books & stationery",
  "Restaurant / dhaba / sweet shop",
  "Bakery / caterer / cloud kitchen",
  "Hotel / guest house / resort",
  "Travel agency / tour operator",
  "Logistics / transport / fleet",
  "Courier / delivery",
  "Warehousing / cold storage",
  "Construction / contractor",
  "Real estate / builder",
  "Interior / architecture",
  "Electrical / plumbing / AC services",
  "Security services",
  "Facility management / housekeeping",
  "Manpower / staffing agency",
  "Automobile dealer / showroom",
  "Garage / service station",
  "Petrol pump / fuel station",
  "Hospital / nursing home",
  "Clinic / diagnostic lab",
  "School",
  "College / coaching / training institute",
  "IT services / software",
  "BPO / call centre",
  "Digital marketing / advertising",
  "CA / accounting / tax firm",
  "Legal / consulting",
  "Finance / NBFC / insurance agency",
  "Agriculture / farm",
  "Agri-inputs / seeds / fertiliser dealer",
  "Dairy / poultry / fisheries",
  "Mining / quarry / brick kiln",
  "Salon / spa / beauty",
  "Gym / fitness / sports",
  "Event management / wedding services",
  "Photography / studio",
  "Laundry / dry cleaning",
  "Cinema / entertainment",
  "NGO / trust / religious institution",
  "Government contractor / PSU vendor",
  "Other",
] as const;

export const STATES_AND_UTS = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export type IndianState = (typeof STATES_AND_UTS)[number];

/** What the registrant does in the company. All become its Owner in FlowHRMS. */
export const SIGNUP_ROLES = [
  "Owner / Proprietor",
  "Partner / Director",
  "Manager",
  "HR / Admin",
  "Accountant",
  "Other",
] as const;

export const HEARD_FROM = [
  "Google search",
  "Friend or family",
  "Social media (Facebook, Instagram, LinkedIn)",
  "YouTube",
  "WhatsApp",
  "My CA / accountant",
  "Flowacord team",
  "Other",
] as const;

/** 3-digit pincode prefixes that differ from their 2-digit region. */
const PREFIX3: Record<string, IndianState> = {
  "160": "Chandigarh",
  "194": "Ladakh",
  "246": "Uttarakhand",
  "247": "Uttarakhand",
  "248": "Uttarakhand",
  "249": "Uttarakhand",
  "262": "Uttarakhand",
  "263": "Uttarakhand",
  "403": "Goa",
  "605": "Puducherry",
  "737": "Sikkim",
  "744": "Andaman and Nicobar Islands",
  "790": "Arunachal Pradesh",
  "791": "Arunachal Pradesh",
  "792": "Arunachal Pradesh",
  "793": "Meghalaya",
  "794": "Meghalaya",
  "795": "Manipur",
  "796": "Mizoram",
  "797": "Nagaland",
  "798": "Nagaland",
  "799": "Tripura",
  "814": "Jharkhand",
  "815": "Jharkhand",
  "816": "Jharkhand",
  "825": "Jharkhand",
  "826": "Jharkhand",
  "827": "Jharkhand",
  "828": "Jharkhand",
  "829": "Jharkhand",
  "831": "Jharkhand",
  "832": "Jharkhand",
  "833": "Jharkhand",
  "834": "Jharkhand",
  "835": "Jharkhand",
};

/** 2-digit postal regions. */
const PREFIX2: Record<string, IndianState> = {
  "11": "Delhi",
  "12": "Haryana",
  "13": "Haryana",
  "14": "Punjab",
  "15": "Punjab",
  "16": "Punjab",
  "17": "Himachal Pradesh",
  "18": "Jammu and Kashmir",
  "19": "Jammu and Kashmir",
  "20": "Uttar Pradesh",
  "21": "Uttar Pradesh",
  "22": "Uttar Pradesh",
  "23": "Uttar Pradesh",
  "24": "Uttar Pradesh",
  "25": "Uttar Pradesh",
  "26": "Uttar Pradesh",
  "27": "Uttar Pradesh",
  "28": "Uttar Pradesh",
  "30": "Rajasthan",
  "31": "Rajasthan",
  "32": "Rajasthan",
  "33": "Rajasthan",
  "34": "Rajasthan",
  "36": "Gujarat",
  "37": "Gujarat",
  "38": "Gujarat",
  "39": "Gujarat",
  "40": "Maharashtra",
  "41": "Maharashtra",
  "42": "Maharashtra",
  "43": "Maharashtra",
  "44": "Maharashtra",
  "45": "Madhya Pradesh",
  "46": "Madhya Pradesh",
  "47": "Madhya Pradesh",
  "48": "Madhya Pradesh",
  "49": "Chhattisgarh",
  "50": "Telangana",
  "51": "Andhra Pradesh",
  "52": "Andhra Pradesh",
  "53": "Andhra Pradesh",
  "56": "Karnataka",
  "57": "Karnataka",
  "58": "Karnataka",
  "59": "Karnataka",
  "60": "Tamil Nadu",
  "61": "Tamil Nadu",
  "62": "Tamil Nadu",
  "63": "Tamil Nadu",
  "64": "Tamil Nadu",
  "67": "Kerala",
  "68": "Kerala",
  "69": "Kerala",
  "70": "West Bengal",
  "71": "West Bengal",
  "72": "West Bengal",
  "73": "West Bengal",
  "74": "West Bengal",
  "75": "Odisha",
  "76": "Odisha",
  "77": "Odisha",
  "78": "Assam",
  "80": "Bihar",
  "81": "Bihar",
  "82": "Bihar",
  "83": "Bihar",
  "84": "Bihar",
  "85": "Bihar",
};

/** A valid Indian pincode: 6 digits, not starting with 0. */
export function isPincode(value: string): boolean {
  return /^[1-9]\d{5}$/.test(value.trim());
}

/**
 * The state a pincode most likely belongs to, from its postal region.
 * A suggestion only — the form lets the person change it, because postal
 * regions and state borders do not line up everywhere.
 */
export function stateForPincode(pincode: string): IndianState | null {
  const p = pincode.trim();
  if (!isPincode(p)) return null;
  return PREFIX3[p.slice(0, 3)] ?? PREFIX2[p.slice(0, 2)] ?? null;
}
