import { cn } from "@/lib/cn";
import { FLOWACORD } from "./FlowacordMark";

/**
 * The FlowHRMS wordmark — the product lockup, built from the approved
 * Flowacord logo, not drawn afresh. GENERATED by scripts/build-wordmark.mjs;
 * edit that script, not this file.
 *
 * Everything up to and including "Flow" is the official vector
 * (public/brand/flowacord-logo-light.svg, viewBox 652.69 × 113.84): the
 * icon mark and the four outlined glyphs of "Flow" in the company's
 * primary face, coordinates untouched. "acord" is replaced by "HRMS", set
 * in the brand's secondary face — Poppins SemiBold Italic — in the same
 * lavender, on the same baseline (y = 98.71) and to the same cap height.
 * That mirrors the two-part construction of the company mark exactly.
 *
 * The dark-background variant of the official logo is the same drawing at
 * a different scale with "Flow" in paper white, so one geometry serves
 * both tones and only the fill changes.
 */

/** Fill classes from the official file: 1 lavender-light, 2 lavender, 3 purple. */
const FILL = {
  1: FLOWACORD.lavenderLight,
  2: FLOWACORD.lavender,
  3: FLOWACORD.purple,
} as const;

const FLOW_INK = { light: FLOWACORD.navy, dark: FLOWACORD.paper } as const;

/** Right edge of the "w" is 334; capitals need a little air that lowercase "acord" did not. */
const HRMS_X = 352;
const BASELINE = 98.71;
/** Poppins cap height is 0.70 em; the "F" stands 57.3 units tall. */
const HRMS_SIZE = 82;
const VIEW_W = 612;
const VIEW_H = 113.84;

const FONT = "var(--font-poppins-display, var(--font-poppins, Poppins, sans-serif))";

export function FlowHRMSWordmark({
  height = 28,
  tone = "light",
  className,
  title = "FlowHRMS",
}: {
  height?: number;
  /** "light" = on white/paper. "dark" = on the navy ground. */
  tone?: "light" | "dark";
  className?: string;
  title?: string | null;
}) {
  const width = (height * VIEW_W) / VIEW_H;
  return (
    <svg
      width={width}
      height={height}
      viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : "true"}
      focusable="false"
      className={className}
    >
      {title && <title>{title}</title>}
      <rect fill={FILL[1]} width="32.79" height="32.79" rx="16.4" transform="translate(-6.79 16.4) rotate(-45)" />
      <path fill={FILL[2]} d="M28,45.32a16.4,16.4,0,0,0-23.19,0h0a16.4,16.4,0,0,0,0,23.19h0a16.39,16.39,0,0,0,23.19,0h0a16.39,16.39,0,0,0,0-23.19Z" />
      <rect fill={FILL[3]} y="81.04" width="32.79" height="32.79" rx="16.4" transform="translate(-64.1 40.13) rotate(-45)" />
      <rect fill={FILL[2]} x="39.08" width="32.79" height="32.79" rx="16.4" transform="translate(4.65 44.03) rotate(-45)" />
      <path fill={FILL[3]} d="M106.14,4.8h0A16.4,16.4,0,0,0,83,4.8h0A16.4,16.4,0,0,0,83,28h0a16.39,16.39,0,0,0,23.19,0h0A16.39,16.39,0,0,0,106.14,4.8Z" />
      <path fill={FILL[2]} d="M45.41,76.57V48.13a1.27,1.27,0,0,1,1.27-1.28H75.12A1.27,1.27,0,0,1,76,49L47.58,77.47A1.27,1.27,0,0,1,45.41,76.57Z" />
      <g fill={FLOW_INK[tone]}>
        <polygon points="122.96 98.71 140.63 98.71 144.33 72.21 168.67 72.21 171.03 55.57 146.69 55.57 148.23 44.48 176.48 44.48 178.84 27.84 132.93 27.84 122.96 98.71" />
        <path d="M204,24.75H187.37l-7.91,56.91c-1.64,11.3,3.9,17,16.64,17h5.75L204,83.51h-3.29c-3.18,0-4.72-1.65-4.21-4.62Z" />
        <path d="M240.88,45.09c-16.22,0-30.09,11.81-32.25,27.43s8.22,27.42,24.45,27.42,30.09-11.81,32.25-27.42S257,45.09,240.88,45.09Zm7.3,27.43a13,13,0,0,1-12.84,11.3c-6.47,0-10.48-4.83-9.66-11.3a13,13,0,0,1,12.84-11.3C245,61.22,249,66.05,248.18,72.52Z" />
        <path d="M333.77,45.77c2.54,6,.28,12.16-3,20.38l-4.52,10.68-4.52-30.51h-17l-13,30.41-4-30.41h-19l10.89,52.39h17.05l13.46-31.84,4.42,31.84h17l14.17-29c4.83-10,7.81-17.36,5.16-24Z" />
      </g>
      <text
        x={HRMS_X}
        y={BASELINE}
        fill={FLOWACORD.lavender}
        fontFamily={FONT}
        fontWeight={600}
        fontStyle="italic"
        fontSize={HRMS_SIZE}
        letterSpacing="-0.5"
      >
        HRMS
      </text>
    </svg>
  );
}

/**
 * Wordmark plus the parent-brand line, for headers and sign-in.
 * "by Flowacord" is text, not part of the mark: it takes the surface's
 * muted ink and is the first thing to drop on a narrow screen. A caller
 * that passes className owns the display value (e.g. "hidden md:inline-flex").
 */
export function FlowHRMSLockup({
  height = 28,
  tone = "light",
  byline = true,
  className,
}: {
  height?: number;
  tone?: "light" | "dark";
  byline?: boolean;
  className?: string;
}) {
  const sub = tone === "dark" ? "rgba(245,245,245,.72)" : "rgba(52,50,127,.72)";
  return (
    <span className={cn("items-baseline gap-2.5", className ?? "inline-flex")}>
      <FlowHRMSWordmark height={height} tone={tone} />
      {byline && (
        <span
          style={{
            fontFamily: FONT,
            fontWeight: 500,
            fontSize: Math.max(11, Math.round(height * 0.42)),
            letterSpacing: "0.01em",
            color: sub,
            whiteSpace: "nowrap",
          }}
        >
          by Flowacord
        </span>
      )}
    </span>
  );
}
